driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  client_rb:
    log_level: :info

verifier:
  name: inspec

platforms:
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
  - name: windows-2016-chef-12
    driver_config:
      box: chef/windows-server-2016-standard
    provisioner:
      require_chef_omnibus: 12.14.89

suites:
  - name: default
    run_list:
      - recipe[iis::default]
  - name: app
    run_list:
      - recipe[test::app]
  - name: config
    run_list:
      - recipe[test::config]
  - name: module
    run_list:
      - recipe[test::module]
  - name: pool
    run_list:
      - recipe[test::pool]
  - name: root
    run_list:
      - recipe[test::root]
  - name: section
    run_list:
      - recipe[test::section]
  - name: site
    run_list:
      - recipe[test::site]
  - name: vdir
    run_list:
      - recipe[test::vdir]
